# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cultura-Visual' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cultura-Visual
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Charts'

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  target 'Cultura-VisualTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Cultura-VisualUITests' do
    # Pods for testing
  end

end
